// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMaskingRule(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddMaskingRule'](arg1, arg2, arg3);
}

export function AddProjectSource(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AddProjectSource'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function AddRequestToCollection(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddRequestToCollection'](arg1, arg2, arg3);
}

export function AddSSOProvider(arg1) {
  return window['go']['main']['App']['AddSSOProvider'](arg1);
}

export function AddSpecEndpoint(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddSpecEndpoint'](arg1, arg2, arg3, arg4);
}

export function AddTestGroup(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddTestGroup'](arg1, arg2, arg3);
}

export function AnalyzeAllCollectionsAgentLens() {
  return window['go']['main']['App']['AnalyzeAllCollectionsAgentLens']();
}

export function AnalyzeCollectionAgentLens(arg1) {
  return window['go']['main']['App']['AnalyzeCollectionAgentLens'](arg1);
}

export function AppDataDir() {
  return window['go']['main']['App']['AppDataDir']();
}

export function ArchiveProject(arg1) {
  return window['go']['main']['App']['ArchiveProject'](arg1);
}

export function AuthenticateSSO(arg1, arg2) {
  return window['go']['main']['App']['AuthenticateSSO'](arg1, arg2);
}

export function BuildSOAPEnvelope(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['BuildSOAPEnvelope'](arg1, arg2, arg3, arg4, arg5);
}

export function CancelRequest() {
  return window['go']['main']['App']['CancelRequest']();
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ClearAllCookies() {
  return window['go']['main']['App']['ClearAllCookies']();
}

export function ClearCapturedRequests() {
  return window['go']['main']['App']['ClearCapturedRequests']();
}

export function ClearCookiesForDomain(arg1) {
  return window['go']['main']['App']['ClearCookiesForDomain'](arg1);
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function CommitAndPush(arg1) {
  return window['go']['main']['App']['CommitAndPush'](arg1);
}

export function ComputeDevStats() {
  return window['go']['main']['App']['ComputeDevStats']();
}

export function ConnectSocket(arg1, arg2) {
  return window['go']['main']['App']['ConnectSocket'](arg1, arg2);
}

export function ConnectSocketIO(arg1) {
  return window['go']['main']['App']['ConnectSocketIO'](arg1);
}

export function CreateBranch(arg1) {
  return window['go']['main']['App']['CreateBranch'](arg1);
}

export function CreateCollection(arg1) {
  return window['go']['main']['App']['CreateCollection'](arg1);
}

export function CreateEnvironment(arg1) {
  return window['go']['main']['App']['CreateEnvironment'](arg1);
}

export function CreateProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2, arg3);
}

export function CreateSchedule(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateSchedule'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateSpec(arg1, arg2) {
  return window['go']['main']['App']['CreateSpec'](arg1, arg2);
}

export function CreateTestSuite(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTestSuite'](arg1, arg2, arg3);
}

export function CreateWorkspace(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateWorkspace'](arg1, arg2, arg3);
}

export function DecodeJWT(arg1) {
  return window['go']['main']['App']['DecodeJWT'](arg1);
}

export function DeleteCollection(arg1) {
  return window['go']['main']['App']['DeleteCollection'](arg1);
}

export function DeleteEncryptionKey() {
  return window['go']['main']['App']['DeleteEncryptionKey']();
}

export function DeleteEnvironment(arg1) {
  return window['go']['main']['App']['DeleteEnvironment'](arg1);
}

export function DeleteHistoryEntry(arg1) {
  return window['go']['main']['App']['DeleteHistoryEntry'](arg1);
}

export function DeleteSavedRequest(arg1) {
  return window['go']['main']['App']['DeleteSavedRequest'](arg1);
}

export function DeleteSavedRequests(arg1) {
  return window['go']['main']['App']['DeleteSavedRequests'](arg1);
}

export function DeleteSchedule(arg1) {
  return window['go']['main']['App']['DeleteSchedule'](arg1);
}

export function DeleteSecret(arg1) {
  return window['go']['main']['App']['DeleteSecret'](arg1);
}

export function DeleteTestGroup(arg1, arg2) {
  return window['go']['main']['App']['DeleteTestGroup'](arg1, arg2);
}

export function DeleteTestSuite(arg1) {
  return window['go']['main']['App']['DeleteTestSuite'](arg1);
}

export function DeleteWorkspace(arg1) {
  return window['go']['main']['App']['DeleteWorkspace'](arg1);
}

export function DetectSchemaDrift(arg1) {
  return window['go']['main']['App']['DetectSchemaDrift'](arg1);
}

export function DiagnoseWithAI(arg1, arg2) {
  return window['go']['main']['App']['DiagnoseWithAI'](arg1, arg2);
}

export function DisconnectSocket() {
  return window['go']['main']['App']['DisconnectSocket']();
}

export function DisconnectSocketIO() {
  return window['go']['main']['App']['DisconnectSocketIO']();
}

export function DownloadBinaryResponse(arg1, arg2) {
  return window['go']['main']['App']['DownloadBinaryResponse'](arg1, arg2);
}

export function EmitSocketIOEvent(arg1, arg2) {
  return window['go']['main']['App']['EmitSocketIOEvent'](arg1, arg2);
}

export function EnsureProjectForPath(arg1, arg2) {
  return window['go']['main']['App']['EnsureProjectForPath'](arg1, arg2);
}

export function ExportCollectionHTML(arg1, arg2) {
  return window['go']['main']['App']['ExportCollectionHTML'](arg1, arg2);
}

export function ExportCollectionMarkdown(arg1, arg2) {
  return window['go']['main']['App']['ExportCollectionMarkdown'](arg1, arg2);
}

export function ExportEnvironmentJSON(arg1) {
  return window['go']['main']['App']['ExportEnvironmentJSON'](arg1);
}

export function ExportExtension(arg1) {
  return window['go']['main']['App']['ExportExtension'](arg1);
}

export function ExportHoppscotch(arg1) {
  return window['go']['main']['App']['ExportHoppscotch'](arg1);
}

export function ExportInsomnia(arg1) {
  return window['go']['main']['App']['ExportInsomnia'](arg1);
}

export function ExportMCPServerAgentLens() {
  return window['go']['main']['App']['ExportMCPServerAgentLens']();
}

export function ExportOpenAPI(arg1) {
  return window['go']['main']['App']['ExportOpenAPI'](arg1);
}

export function ExportOpenAPIFiles(arg1) {
  return window['go']['main']['App']['ExportOpenAPIFiles'](arg1);
}

export function ExportPostman(arg1) {
  return window['go']['main']['App']['ExportPostman'](arg1);
}

export function ExportReportAsHTML(arg1, arg2) {
  return window['go']['main']['App']['ExportReportAsHTML'](arg1, arg2);
}

export function ExportReportAsJSON(arg1) {
  return window['go']['main']['App']['ExportReportAsJSON'](arg1);
}

export function FetchSpecFromURL(arg1) {
  return window['go']['main']['App']['FetchSpecFromURL'](arg1);
}

export function GRPCInvoke(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GRPCInvoke'](arg1, arg2, arg3, arg4, arg5);
}

export function GRPCStreamInvoke(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GRPCStreamInvoke'](arg1, arg2, arg3, arg4, arg5);
}

export function GenerateAssertions(arg1, arg2) {
  return window['go']['main']['App']['GenerateAssertions'](arg1, arg2);
}

export function GenerateCLIRunner(arg1) {
  return window['go']['main']['App']['GenerateCLIRunner'](arg1);
}

export function GenerateCLIRunnerScript(arg1) {
  return window['go']['main']['App']['GenerateCLIRunnerScript'](arg1);
}

export function GenerateCurl(arg1, arg2) {
  return window['go']['main']['App']['GenerateCurl'](arg1, arg2);
}

export function GenerateEncryptionKey() {
  return window['go']['main']['App']['GenerateEncryptionKey']();
}

export function GenerateGitHubAction(arg1, arg2) {
  return window['go']['main']['App']['GenerateGitHubAction'](arg1, arg2);
}

export function GenerateGitLabCI(arg1, arg2) {
  return window['go']['main']['App']['GenerateGitLabCI'](arg1, arg2);
}

export function GenerateHTMLReport(arg1, arg2) {
  return window['go']['main']['App']['GenerateHTMLReport'](arg1, arg2);
}

export function GenerateJSONReport(arg1) {
  return window['go']['main']['App']['GenerateJSONReport'](arg1);
}

export function GenerateJenkins(arg1, arg2) {
  return window['go']['main']['App']['GenerateJenkins'](arg1, arg2);
}

export function GenerateJestTest(arg1, arg2) {
  return window['go']['main']['App']['GenerateJestTest'](arg1, arg2);
}

export function GeneratePlaywrightTest(arg1, arg2) {
  return window['go']['main']['App']['GeneratePlaywrightTest'](arg1, arg2);
}

export function GetAISettings() {
  return window['go']['main']['App']['GetAISettings']();
}

export function GetActiveContributors() {
  return window['go']['main']['App']['GetActiveContributors']();
}

export function GetActiveProject() {
  return window['go']['main']['App']['GetActiveProject']();
}

export function GetActiveWorkspace() {
  return window['go']['main']['App']['GetActiveWorkspace']();
}

export function GetAirGapConfig() {
  return window['go']['main']['App']['GetAirGapConfig']();
}

export function GetAutoSync() {
  return window['go']['main']['App']['GetAutoSync']();
}

export function GetBadges() {
  return window['go']['main']['App']['GetBadges']();
}

export function GetBranches() {
  return window['go']['main']['App']['GetBranches']();
}

export function GetCapturedRequests() {
  return window['go']['main']['App']['GetCapturedRequests']();
}

export function GetCollections() {
  return window['go']['main']['App']['GetCollections']();
}

export function GetCollectionsSummary() {
  return window['go']['main']['App']['GetCollectionsSummary']();
}

export function GetCommunityConfig() {
  return window['go']['main']['App']['GetCommunityConfig']();
}

export function GetCookies() {
  return window['go']['main']['App']['GetCookies']();
}

export function GetDevProfile() {
  return window['go']['main']['App']['GetDevProfile']();
}

export function GetEnvironments() {
  return window['go']['main']['App']['GetEnvironments']();
}

export function GetFeatureRequests() {
  return window['go']['main']['App']['GetFeatureRequests']();
}

export function GetGitConflictFiles() {
  return window['go']['main']['App']['GetGitConflictFiles']();
}

export function GetGitDiff(arg1, arg2) {
  return window['go']['main']['App']['GetGitDiff'](arg1, arg2);
}

export function GetGitDiffContent(arg1) {
  return window['go']['main']['App']['GetGitDiffContent'](arg1);
}

export function GetGitLog(arg1) {
  return window['go']['main']['App']['GetGitLog'](arg1);
}

export function GetGitStashList() {
  return window['go']['main']['App']['GetGitStashList']();
}

export function GetGitStatus() {
  return window['go']['main']['App']['GetGitStatus']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetInterceptorStatus() {
  return window['go']['main']['App']['GetInterceptorStatus']();
}

export function GetLocks() {
  return window['go']['main']['App']['GetLocks']();
}

export function GetMaskingRules() {
  return window['go']['main']['App']['GetMaskingRules']();
}

export function GetMockStatus() {
  return window['go']['main']['App']['GetMockStatus']();
}

export function GetPlugins() {
  return window['go']['main']['App']['GetPlugins']();
}

export function GetProfile() {
  return window['go']['main']['App']['GetProfile']();
}

export function GetProjectActivity(arg1) {
  return window['go']['main']['App']['GetProjectActivity'](arg1);
}

export function GetProjectCapabilities(arg1) {
  return window['go']['main']['App']['GetProjectCapabilities'](arg1);
}

export function GetProjectJobs(arg1) {
  return window['go']['main']['App']['GetProjectJobs'](arg1);
}

export function GetProxyConfig() {
  return window['go']['main']['App']['GetProxyConfig']();
}

export function GetPublicProfile() {
  return window['go']['main']['App']['GetPublicProfile']();
}

export function GetRecipe(arg1) {
  return window['go']['main']['App']['GetRecipe'](arg1);
}

export function GetRecipeCategories() {
  return window['go']['main']['App']['GetRecipeCategories']();
}

export function GetRecipes() {
  return window['go']['main']['App']['GetRecipes']();
}

export function GetRequestDetail(arg1) {
  return window['go']['main']['App']['GetRequestDetail'](arg1);
}

export function GetSSOProviders() {
  return window['go']['main']['App']['GetSSOProviders']();
}

export function GetSchedulerHistory(arg1, arg2) {
  return window['go']['main']['App']['GetSchedulerHistory'](arg1, arg2);
}

export function GetSchedules() {
  return window['go']['main']['App']['GetSchedules']();
}

export function GetSocketIOState() {
  return window['go']['main']['App']['GetSocketIOState']();
}

export function GetSocketState() {
  return window['go']['main']['App']['GetSocketState']();
}

export function GetSpecEndpoints(arg1) {
  return window['go']['main']['App']['GetSpecEndpoints'](arg1);
}

export function GetTelemetryConfig() {
  return window['go']['main']['App']['GetTelemetryConfig']();
}

export function GetTelemetryEvents(arg1) {
  return window['go']['main']['App']['GetTelemetryEvents'](arg1);
}

export function GetTelemetryPreview() {
  return window['go']['main']['App']['GetTelemetryPreview']();
}

export function GetTestSuites() {
  return window['go']['main']['App']['GetTestSuites']();
}

export function GetTierCategories() {
  return window['go']['main']['App']['GetTierCategories']();
}

export function GetTiers() {
  return window['go']['main']['App']['GetTiers']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GetWorkspaces() {
  return window['go']['main']['App']['GetWorkspaces']();
}

export function GitHubCloneRepository(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitHubCloneRepository'](arg1, arg2, arg3);
}

export function GitHubDeletePAT(arg1) {
  return window['go']['main']['App']['GitHubDeletePAT'](arg1);
}

export function GitHubGetViewer(arg1) {
  return window['go']['main']['App']['GitHubGetViewer'](arg1);
}

export function GitHubListRepositories(arg1, arg2) {
  return window['go']['main']['App']['GitHubListRepositories'](arg1, arg2);
}

export function GitHubSavePAT(arg1, arg2) {
  return window['go']['main']['App']['GitHubSavePAT'](arg1, arg2);
}

export function GitMergeBranch(arg1) {
  return window['go']['main']['App']['GitMergeBranch'](arg1);
}

export function GitPopStash() {
  return window['go']['main']['App']['GitPopStash']();
}

export function GitPull() {
  return window['go']['main']['App']['GitPull']();
}

export function GitResolveConflictOurs(arg1) {
  return window['go']['main']['App']['GitResolveConflictOurs'](arg1);
}

export function GitResolveConflictTheirs(arg1) {
  return window['go']['main']['App']['GitResolveConflictTheirs'](arg1);
}

export function GitStash() {
  return window['go']['main']['App']['GitStash']();
}

export function GraphQLExecute(arg1) {
  return window['go']['main']['App']['GraphQLExecute'](arg1);
}

export function GraphQLIntrospect(arg1, arg2) {
  return window['go']['main']['App']['GraphQLIntrospect'](arg1, arg2);
}

export function HasEncryptionKey() {
  return window['go']['main']['App']['HasEncryptionKey']();
}

export function ImportEnvironmentFile() {
  return window['go']['main']['App']['ImportEnvironmentFile']();
}

export function ImportHAR(arg1, arg2) {
  return window['go']['main']['App']['ImportHAR'](arg1, arg2);
}

export function ImportHoppscotch(arg1, arg2) {
  return window['go']['main']['App']['ImportHoppscotch'](arg1, arg2);
}

export function ImportInsomnia(arg1, arg2) {
  return window['go']['main']['App']['ImportInsomnia'](arg1, arg2);
}

export function ImportOpenAPI(arg1) {
  return window['go']['main']['App']['ImportOpenAPI'](arg1);
}

export function ImportPostman(arg1, arg2) {
  return window['go']['main']['App']['ImportPostman'](arg1, arg2);
}

export function ImportPostmanEnvironment(arg1, arg2) {
  return window['go']['main']['App']['ImportPostmanEnvironment'](arg1, arg2);
}

export function ImportPostmanFull(arg1, arg2) {
  return window['go']['main']['App']['ImportPostmanFull'](arg1, arg2);
}

export function InitGit(arg1, arg2) {
  return window['go']['main']['App']['InitGit'](arg1, arg2);
}

export function InstallPlugin(arg1) {
  return window['go']['main']['App']['InstallPlugin'](arg1);
}

export function InstallUpdate(arg1) {
  return window['go']['main']['App']['InstallUpdate'](arg1);
}

export function InvalidateSpec(arg1) {
  return window['go']['main']['App']['InvalidateSpec'](arg1);
}

export function IsUpstashConfigured() {
  return window['go']['main']['App']['IsUpstashConfigured']();
}

export function LinkCollectionSpec(arg1, arg2) {
  return window['go']['main']['App']['LinkCollectionSpec'](arg1, arg2);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListSecrets(arg1) {
  return window['go']['main']['App']['ListSecrets'](arg1);
}

export function LockCollection(arg1) {
  return window['go']['main']['App']['LockCollection'](arg1);
}

export function MQTTClearMessages() {
  return window['go']['main']['App']['MQTTClearMessages']();
}

export function MQTTConnect(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['MQTTConnect'](arg1, arg2, arg3, arg4, arg5);
}

export function MQTTDisconnect() {
  return window['go']['main']['App']['MQTTDisconnect']();
}

export function MQTTGetMessages() {
  return window['go']['main']['App']['MQTTGetMessages']();
}

export function MQTTPublish(arg1, arg2, arg3) {
  return window['go']['main']['App']['MQTTPublish'](arg1, arg2, arg3);
}

export function MQTTStatus() {
  return window['go']['main']['App']['MQTTStatus']();
}

export function MaskText(arg1) {
  return window['go']['main']['App']['MaskText'](arg1);
}

export function MoveRequest(arg1, arg2) {
  return window['go']['main']['App']['MoveRequest'](arg1, arg2);
}

export function OAuth2AuthorizeURL(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['OAuth2AuthorizeURL'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function OAuth2Exchange(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['OAuth2Exchange'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function OAuth2Refresh(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['OAuth2Refresh'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function OpenProject(arg1) {
  return window['go']['main']['App']['OpenProject'](arg1);
}

export function OpenWorkspaceFromFolder(arg1) {
  return window['go']['main']['App']['OpenWorkspaceFromFolder'](arg1);
}

export function ParseCurl(arg1) {
  return window['go']['main']['App']['ParseCurl'](arg1);
}

export function PickFile(arg1, arg2) {
  return window['go']['main']['App']['PickFile'](arg1, arg2);
}

export function PickFolder(arg1) {
  return window['go']['main']['App']['PickFolder'](arg1);
}

export function PreviewOpenAPI(arg1) {
  return window['go']['main']['App']['PreviewOpenAPI'](arg1);
}

export function PreviewToolAgentLens(arg1, arg2) {
  return window['go']['main']['App']['PreviewToolAgentLens'](arg1, arg2);
}

export function PublishDevProfile() {
  return window['go']['main']['App']['PublishDevProfile']();
}

export function PullFromStoplight(arg1, arg2) {
  return window['go']['main']['App']['PullFromStoplight'](arg1, arg2);
}

export function PullFromSwaggerHub(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PullFromSwaggerHub'](arg1, arg2, arg3, arg4);
}

export function PushToStoplight(arg1, arg2, arg3) {
  return window['go']['main']['App']['PushToStoplight'](arg1, arg2, arg3);
}

export function PushToSwaggerHub(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['PushToSwaggerHub'](arg1, arg2, arg3, arg4, arg5);
}

export function QueryAuditLog(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['QueryAuditLog'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function RBACCheck(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RBACCheck'](arg1, arg2, arg3, arg4);
}

export function RBACGrant(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RBACGrant'](arg1, arg2, arg3, arg4);
}

export function RBACList(arg1, arg2) {
  return window['go']['main']['App']['RBACList'](arg1, arg2);
}

export function RBACRevoke(arg1, arg2) {
  return window['go']['main']['App']['RBACRevoke'](arg1, arg2);
}

export function ReadFileText(arg1) {
  return window['go']['main']['App']['ReadFileText'](arg1);
}

export function RelocateWorkspace(arg1, arg2) {
  return window['go']['main']['App']['RelocateWorkspace'](arg1, arg2);
}

export function RemoveMaskingRule(arg1) {
  return window['go']['main']['App']['RemoveMaskingRule'](arg1);
}

export function RemovePlugin(arg1) {
  return window['go']['main']['App']['RemovePlugin'](arg1);
}

export function RemoveProjectSource(arg1, arg2) {
  return window['go']['main']['App']['RemoveProjectSource'](arg1, arg2);
}

export function RemoveSSOProvider(arg1) {
  return window['go']['main']['App']['RemoveSSOProvider'](arg1);
}

export function RemoveSpecEndpoint(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoveSpecEndpoint'](arg1, arg2, arg3);
}

export function RenameCollection(arg1, arg2) {
  return window['go']['main']['App']['RenameCollection'](arg1, arg2);
}

export function RenameWorkspace(arg1, arg2) {
  return window['go']['main']['App']['RenameWorkspace'](arg1, arg2);
}

export function ReorderCollection(arg1, arg2) {
  return window['go']['main']['App']['ReorderCollection'](arg1, arg2);
}

export function ReorderRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReorderRequest'](arg1, arg2, arg3);
}

export function RestartApp() {
  return window['go']['main']['App']['RestartApp']();
}

export function RotateSecret(arg1, arg2) {
  return window['go']['main']['App']['RotateSecret'](arg1, arg2);
}

export function RunCollection(arg1, arg2) {
  return window['go']['main']['App']['RunCollection'](arg1, arg2);
}

export function RunCollectionWithConcurrency(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunCollectionWithConcurrency'](arg1, arg2, arg3);
}

export function RunCollectionWithConfig(arg1) {
  return window['go']['main']['App']['RunCollectionWithConfig'](arg1);
}

export function RunEvalAgentLens() {
  return window['go']['main']['App']['RunEvalAgentLens']();
}

export function RunLoadTest(arg1) {
  return window['go']['main']['App']['RunLoadTest'](arg1);
}

export function RunProjectScan(arg1, arg2) {
  return window['go']['main']['App']['RunProjectScan'](arg1, arg2);
}

export function RunRepoAutomation(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RunRepoAutomation'](arg1, arg2, arg3, arg4);
}

export function SaveAISettings(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveAISettings'](arg1, arg2, arg3, arg4);
}

export function SaveCapturedResponse(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveCapturedResponse'](arg1, arg2, arg3);
}

export function SaveDevProfile(arg1) {
  return window['go']['main']['App']['SaveDevProfile'](arg1);
}

export function SaveGeneratedTest(arg1, arg2) {
  return window['go']['main']['App']['SaveGeneratedTest'](arg1, arg2);
}

export function SaveResponseToRequest(arg1, arg2) {
  return window['go']['main']['App']['SaveResponseToRequest'](arg1, arg2);
}

export function SaveSchemaSnapshot(arg1) {
  return window['go']['main']['App']['SaveSchemaSnapshot'](arg1);
}

export function SaveTextResponse(arg1, arg2) {
  return window['go']['main']['App']['SaveTextResponse'](arg1, arg2);
}

export function SaveUpstashConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveUpstashConfig'](arg1, arg2);
}

export function SendNotification(arg1, arg2) {
  return window['go']['main']['App']['SendNotification'](arg1, arg2);
}

export function SendRequest(arg1) {
  return window['go']['main']['App']['SendRequest'](arg1);
}

export function SendSocketIOMessage(arg1) {
  return window['go']['main']['App']['SendSocketIOMessage'](arg1);
}

export function SendSocketMessage(arg1) {
  return window['go']['main']['App']['SendSocketMessage'](arg1);
}

export function SetActiveEnvironment(arg1) {
  return window['go']['main']['App']['SetActiveEnvironment'](arg1);
}

export function SetAirGapConfig(arg1) {
  return window['go']['main']['App']['SetAirGapConfig'](arg1);
}

export function SetAutoSync(arg1) {
  return window['go']['main']['App']['SetAutoSync'](arg1);
}

export function SetCollectionVariables(arg1, arg2) {
  return window['go']['main']['App']['SetCollectionVariables'](arg1, arg2);
}

export function SetDevProfilePublic(arg1) {
  return window['go']['main']['App']['SetDevProfilePublic'](arg1);
}

export function SetDiscordURL(arg1) {
  return window['go']['main']['App']['SetDiscordURL'](arg1);
}

export function SetEncryptionPassphrase(arg1) {
  return window['go']['main']['App']['SetEncryptionPassphrase'](arg1);
}

export function SetEnvVar(arg1, arg2) {
  return window['go']['main']['App']['SetEnvVar'](arg1, arg2);
}

export function SetProxyConfig(arg1) {
  return window['go']['main']['App']['SetProxyConfig'](arg1);
}

export function SetRouteOverride(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetRouteOverride'](arg1, arg2, arg3);
}

export function SetTelemetryEnabled(arg1) {
  return window['go']['main']['App']['SetTelemetryEnabled'](arg1);
}

export function StartInterceptor() {
  return window['go']['main']['App']['StartInterceptor']();
}

export function StartMockServer(arg1) {
  return window['go']['main']['App']['StartMockServer'](arg1);
}

export function StopInterceptor() {
  return window['go']['main']['App']['StopInterceptor']();
}

export function StopMockServer() {
  return window['go']['main']['App']['StopMockServer']();
}

export function StoreSecret(arg1) {
  return window['go']['main']['App']['StoreSecret'](arg1);
}

export function SwitchBranch(arg1) {
  return window['go']['main']['App']['SwitchBranch'](arg1);
}

export function SwitchWorkspace(arg1) {
  return window['go']['main']['App']['SwitchWorkspace'](arg1);
}

export function ToggleMaskingRule(arg1, arg2) {
  return window['go']['main']['App']['ToggleMaskingRule'](arg1, arg2);
}

export function ToggleMockRecording(arg1) {
  return window['go']['main']['App']['ToggleMockRecording'](arg1);
}

export function ToggleSSOProvider(arg1) {
  return window['go']['main']['App']['ToggleSSOProvider'](arg1);
}

export function UnlockCollection(arg1) {
  return window['go']['main']['App']['UnlockCollection'](arg1);
}

export function UpdateCollectionScripts(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateCollectionScripts'](arg1, arg2, arg3);
}

export function UpdateEnvironment(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateEnvironment'](arg1, arg2, arg3);
}

export function UpdateHistoryEntry(arg1, arg2) {
  return window['go']['main']['App']['UpdateHistoryEntry'](arg1, arg2);
}

export function UpdateProfile(arg1, arg2) {
  return window['go']['main']['App']['UpdateProfile'](arg1, arg2);
}

export function UpdateProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateProject'](arg1, arg2, arg3);
}

export function UpdateSavedRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateSavedRequest'](arg1, arg2, arg3);
}

export function UpdateSchedule(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateSchedule'](arg1, arg2, arg3, arg4);
}

export function UpdateScriptRules(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateScriptRules'](arg1, arg2, arg3);
}

export function UpdateTestGroup(arg1, arg2) {
  return window['go']['main']['App']['UpdateTestGroup'](arg1, arg2);
}

export function UpdateTestSuite(arg1) {
  return window['go']['main']['App']['UpdateTestSuite'](arg1);
}

export function UpvoteFeatureRequest(arg1) {
  return window['go']['main']['App']['UpvoteFeatureRequest'](arg1);
}
