// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {projects} from '../models';
import {models} from '../models';
import {agentlens} from '../models';
import {updater} from '../models';
import {profile} from '../models';
import {workspaces} from '../models';
import {schema} from '../models';
import {main} from '../models';
import {git} from '../models';
import {interceptor} from '../models';
import {cookies} from '../models';
import {environments} from '../models';
import {locks} from '../models';
import {plugin} from '../models';
import {history} from '../models';
import {capabilities} from '../models';
import {jobs} from '../models';
import {scheduler} from '../models';
import {openapi} from '../models';
import {telemetry} from '../models';
import {vault} from '../models';
import {mqtt} from '../models';

export function AddMaskingRule(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AddProjectSource(arg1:string,arg2:string,arg3:projects.SourceType,arg4:string,arg5:string,arg6:string):Promise<projects.ProjectSource>;

export function AddRequestToCollection(arg1:string,arg2:string,arg3:models.RequestPayload):Promise<models.SavedRequest>;

export function AddSSOProvider(arg1:string):Promise<void>;

export function AddSpecEndpoint(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AddTestGroup(arg1:string,arg2:string,arg3:models.TestGroup):Promise<void>;

export function AnalyzeAllCollectionsAgentLens():Promise<agentlens.CollectionScore>;

export function AnalyzeCollectionAgentLens(arg1:string):Promise<agentlens.CollectionScore>;

export function AppDataDir():Promise<string>;

export function ArchiveProject(arg1:string):Promise<void>;

export function AuthenticateSSO(arg1:string,arg2:string):Promise<string>;

export function BuildSOAPEnvelope(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Record<string, string>):Promise<string>;

export function CancelRequest():Promise<void>;

export function CheckForUpdates():Promise<updater.UpdateManifest>;

export function ClearAllCookies():Promise<void>;

export function ClearCapturedRequests():Promise<void>;

export function ClearCookiesForDomain(arg1:string):Promise<void>;

export function ClearHistory():Promise<void>;

export function CommitAndPush(arg1:string):Promise<void>;

export function ComputeDevStats():Promise<profile.DevStats>;

export function ConnectSocket(arg1:string,arg2:string):Promise<void>;

export function ConnectSocketIO(arg1:models.SocketIOConnectRequest):Promise<void>;

export function CreateBranch(arg1:string):Promise<void>;

export function CreateCollection(arg1:string):Promise<models.Collection>;

export function CreateEnvironment(arg1:string):Promise<models.Environment>;

export function CreateProject(arg1:string,arg2:string,arg3:string):Promise<projects.Project>;

export function CreateSchedule(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;

export function CreateSpec(arg1:string,arg2:string):Promise<string>;

export function CreateTestSuite(arg1:string,arg2:string,arg3:string):Promise<models.TestSuite>;

export function CreateWorkspace(arg1:string,arg2:string,arg3:string):Promise<workspaces.Info>;

export function DecodeJWT(arg1:string):Promise<models.JWTDecoded>;

export function DeleteCollection(arg1:string):Promise<void>;

export function DeleteEncryptionKey():Promise<void>;

export function DeleteEnvironment(arg1:string):Promise<void>;

export function DeleteHistoryEntry(arg1:string):Promise<void>;

export function DeleteSavedRequest(arg1:string):Promise<void>;

export function DeleteSavedRequests(arg1:Array<string>):Promise<void>;

export function DeleteSchedule(arg1:string):Promise<void>;

export function DeleteSecret(arg1:string):Promise<void>;

export function DeleteTestGroup(arg1:string,arg2:string):Promise<void>;

export function DeleteTestSuite(arg1:string):Promise<void>;

export function DeleteWorkspace(arg1:string):Promise<void>;

export function DetectSchemaDrift(arg1:string):Promise<schema.Drift>;

export function DiagnoseWithAI(arg1:models.RequestPayload,arg2:models.ResponseResult):Promise<string>;

export function DisconnectSocket():Promise<void>;

export function DisconnectSocketIO():Promise<void>;

export function DownloadBinaryResponse(arg1:Array<number>,arg2:string):Promise<void>;

export function EmitSocketIOEvent(arg1:string,arg2:any):Promise<void>;

export function EnsureProjectForPath(arg1:string,arg2:string):Promise<projects.Project>;

export function ExportCollectionHTML(arg1:string,arg2:main.ExportHTMLDocsOpts):Promise<string>;

export function ExportCollectionMarkdown(arg1:string,arg2:main.ExportMarkdownOpts):Promise<string>;

export function ExportEnvironmentJSON(arg1:string):Promise<void>;

export function ExportExtension(arg1:string):Promise<void>;

export function ExportHoppscotch(arg1:string):Promise<string>;

export function ExportInsomnia(arg1:string):Promise<string>;

export function ExportMCPServerAgentLens():Promise<agentlens.ExportResult>;

export function ExportOpenAPI(arg1:string):Promise<string>;

export function ExportOpenAPIFiles(arg1:string):Promise<Record<string, string>>;

export function ExportPostman(arg1:string):Promise<string>;

export function ExportReportAsHTML(arg1:models.CollectionRunResult,arg2:models.LoadTestResult):Promise<string>;

export function ExportReportAsJSON(arg1:models.CollectionRunResult):Promise<string>;

export function FetchSpecFromURL(arg1:string):Promise<string>;

export function GRPCInvoke(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Record<string, string>):Promise<models.GRPCResponse>;

export function GRPCStreamInvoke(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Record<string, string>):Promise<string>;

export function GenerateAssertions(arg1:models.RequestPayload,arg2:models.ResponseResult):Promise<string>;

export function GenerateCLIRunner(arg1:string):Promise<string>;

export function GenerateCLIRunnerScript(arg1:string):Promise<string>;

export function GenerateCurl(arg1:string,arg2:string):Promise<string>;

export function GenerateEncryptionKey():Promise<void>;

export function GenerateGitHubAction(arg1:string,arg2:string):Promise<string>;

export function GenerateGitLabCI(arg1:string,arg2:string):Promise<string>;

export function GenerateHTMLReport(arg1:models.CollectionRunResult,arg2:models.LoadTestResult):Promise<string>;

export function GenerateJSONReport(arg1:models.CollectionRunResult):Promise<string>;

export function GenerateJenkins(arg1:string,arg2:string):Promise<string>;

export function GenerateJestTest(arg1:string,arg2:boolean):Promise<string>;

export function GeneratePlaywrightTest(arg1:string,arg2:boolean):Promise<string>;

export function GetAISettings():Promise<main.AISettingsResult>;

export function GetActiveContributors():Promise<Array<git.Contributor>>;

export function GetActiveProject():Promise<projects.Project>;

export function GetActiveWorkspace():Promise<workspaces.Info>;

export function GetAirGapConfig():Promise<string>;

export function GetAutoSync():Promise<boolean>;

export function GetBadges():Promise<string>;

export function GetBranches():Promise<Array<string>>;

export function GetCapturedRequests():Promise<Array<interceptor.CapturedRequest>>;

export function GetCollections():Promise<Array<models.Collection>>;

export function GetCollectionsSummary():Promise<Array<models.Collection>>;

export function GetCommunityConfig():Promise<string>;

export function GetCookies():Promise<Array<cookies.CookieInfo>>;

export function GetDevProfile():Promise<profile.DevProfile>;

export function GetEnvironments():Promise<environments.Snapshot>;

export function GetFeatureRequests():Promise<string>;

export function GetGitConflictFiles():Promise<Array<string>>;

export function GetGitDiff(arg1:string,arg2:string):Promise<Array<git.DiffEntry>>;

export function GetGitDiffContent(arg1:string):Promise<string>;

export function GetGitLog(arg1:number):Promise<Array<git.CommitInfo>>;

export function GetGitStashList():Promise<Array<git.StashEntry>>;

export function GetGitStatus():Promise<main.GitStatus>;

export function GetHistory():Promise<Array<models.HistoryEntry>>;

export function GetInterceptorStatus():Promise<main.InterceptorStatus>;

export function GetLocks():Promise<Record<string, locks.LockInfo>>;

export function GetMaskingRules():Promise<string>;

export function GetMockStatus():Promise<main.MockStatus>;

export function GetPlugins():Promise<Array<plugin.RegisteredPlugin>>;

export function GetProfile():Promise<profile.Profile>;

export function GetProjectActivity(arg1:number):Promise<Array<history.Entry>>;

export function GetProjectCapabilities(arg1:string):Promise<Array<capabilities.Snapshot>>;

export function GetProjectJobs(arg1:string):Promise<Array<jobs.Job>>;

export function GetProxyConfig():Promise<string>;

export function GetPublicProfile():Promise<profile.PublicProfile>;

export function GetRecipe(arg1:string):Promise<string>;

export function GetRecipeCategories():Promise<Array<string>>;

export function GetRecipes():Promise<string>;

export function GetRequestDetail(arg1:string):Promise<models.SavedRequest>;

export function GetSSOProviders():Promise<string>;

export function GetSchedulerHistory(arg1:string,arg2:number):Promise<string>;

export function GetSchedules():Promise<Array<scheduler.ScheduledRun>>;

export function GetSocketIOState():Promise<models.SocketState>;

export function GetSocketState():Promise<models.SocketState>;

export function GetSpecEndpoints(arg1:string):Promise<Array<openapi.EndpointSummary>>;

export function GetTelemetryConfig():Promise<main.TelemetryConfig>;

export function GetTelemetryEvents(arg1:number):Promise<Array<telemetry.Event>>;

export function GetTelemetryPreview():Promise<string>;

export function GetTestSuites():Promise<Array<models.TestSuite>>;

export function GetTierCategories():Promise<Array<string>>;

export function GetTiers():Promise<string>;

export function GetVersion():Promise<string>;

export function GetWorkspaces():Promise<Array<workspaces.Info>>;

export function GitHubCloneRepository(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GitHubDeletePAT(arg1:string):Promise<void>;

export function GitHubGetViewer(arg1:string):Promise<string>;

export function GitHubListRepositories(arg1:string,arg2:string):Promise<string>;

export function GitHubSavePAT(arg1:string,arg2:string):Promise<void>;

export function GitMergeBranch(arg1:string):Promise<void>;

export function GitPopStash():Promise<void>;

export function GitPull():Promise<void>;

export function GitResolveConflictOurs(arg1:string):Promise<void>;

export function GitResolveConflictTheirs(arg1:string):Promise<void>;

export function GitStash():Promise<string>;

export function GraphQLExecute(arg1:string):Promise<string>;

export function GraphQLIntrospect(arg1:string,arg2:string):Promise<string>;

export function HasEncryptionKey():Promise<boolean>;

export function ImportEnvironmentFile():Promise<string>;

export function ImportHAR(arg1:string,arg2:string):Promise<number>;

export function ImportHoppscotch(arg1:string,arg2:string):Promise<number>;

export function ImportInsomnia(arg1:string,arg2:string):Promise<number>;

export function ImportOpenAPI(arg1:string):Promise<openapi.ImportResult>;

export function ImportPostman(arg1:string,arg2:string):Promise<number>;

export function ImportPostmanEnvironment(arg1:string,arg2:string):Promise<string>;

export function ImportPostmanFull(arg1:string,arg2:string):Promise<string>;

export function InitGit(arg1:string,arg2:string):Promise<void>;

export function InstallPlugin(arg1:string):Promise<void>;

export function InstallUpdate(arg1:updater.UpdateManifest):Promise<void>;

export function InvalidateSpec(arg1:string):Promise<void>;

export function IsUpstashConfigured():Promise<boolean>;

export function LinkCollectionSpec(arg1:string,arg2:string):Promise<void>;

export function ListProjects():Promise<Array<projects.ProjectSummary>>;

export function ListSecrets(arg1:string):Promise<Array<vault.SecretMetadata>>;

export function LockCollection(arg1:string):Promise<void>;

export function MQTTClearMessages():Promise<void>;

export function MQTTConnect(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function MQTTDisconnect():Promise<void>;

export function MQTTGetMessages():Promise<Array<mqtt.Message>>;

export function MQTTPublish(arg1:string,arg2:string,arg3:number):Promise<void>;

export function MQTTStatus():Promise<string>;

export function MaskText(arg1:string):Promise<string>;

export function MoveRequest(arg1:string,arg2:string):Promise<void>;

export function OAuth2AuthorizeURL(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:boolean):Promise<string>;

export function OAuth2Exchange(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:boolean):Promise<models.OAuth2TokenResponse>;

export function OAuth2Refresh(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:boolean):Promise<models.OAuth2TokenResponse>;

export function OpenProject(arg1:string):Promise<projects.Project>;

export function OpenWorkspaceFromFolder(arg1:string):Promise<workspaces.Info>;

export function ParseCurl(arg1:string):Promise<string>;

export function PickFile(arg1:string,arg2:string):Promise<string>;

export function PickFolder(arg1:string):Promise<string>;

export function PreviewOpenAPI(arg1:string):Promise<void>;

export function PreviewToolAgentLens(arg1:string,arg2:string):Promise<agentlens.ToolDefinition>;

export function PublishDevProfile():Promise<string>;

export function PullFromStoplight(arg1:string,arg2:string):Promise<string>;

export function PullFromSwaggerHub(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function PushToStoplight(arg1:string,arg2:string,arg3:string):Promise<main.RegistryPushResult>;

export function PushToSwaggerHub(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.RegistryPushResult>;

export function QueryAuditLog(arg1:number,arg2:number,arg3:string,arg4:string,arg5:string,arg6:string):Promise<string>;

export function RBACCheck(arg1:string,arg2:string,arg3:string,arg4:string):Promise<boolean>;

export function RBACGrant(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function RBACList(arg1:string,arg2:string):Promise<string>;

export function RBACRevoke(arg1:string,arg2:string):Promise<void>;

export function ReadFileText(arg1:string):Promise<string>;

export function RelocateWorkspace(arg1:string,arg2:string):Promise<void>;

export function RemoveMaskingRule(arg1:string):Promise<void>;

export function RemovePlugin(arg1:string):Promise<void>;

export function RemoveProjectSource(arg1:string,arg2:string):Promise<void>;

export function RemoveSSOProvider(arg1:string):Promise<void>;

export function RemoveSpecEndpoint(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RenameCollection(arg1:string,arg2:string):Promise<void>;

export function RenameWorkspace(arg1:string,arg2:string):Promise<void>;

export function ReorderCollection(arg1:string,arg2:number):Promise<void>;

export function ReorderRequest(arg1:string,arg2:string,arg3:number):Promise<void>;

export function RestartApp():Promise<void>;

export function RotateSecret(arg1:string,arg2:string):Promise<void>;

export function RunCollection(arg1:Array<models.RunnerRequest>,arg2:Record<string, models.Assertion>):Promise<models.CollectionRunResult>;

export function RunCollectionWithConcurrency(arg1:Array<models.RunnerRequest>,arg2:Record<string, models.Assertion>,arg3:number):Promise<models.CollectionRunResult>;

export function RunCollectionWithConfig(arg1:models.RunnerConfig):Promise<models.CollectionRunResult>;

export function RunEvalAgentLens():Promise<agentlens.EvalSuiteResult>;

export function RunLoadTest(arg1:models.LoadTestConfig):Promise<models.LoadTestResult>;

export function RunProjectScan(arg1:string,arg2:string):Promise<string>;

export function RunRepoAutomation(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function SaveAISettings(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SaveCapturedResponse(arg1:string,arg2:string,arg3:models.SavedResponse):Promise<void>;

export function SaveDevProfile(arg1:profile.DevProfile):Promise<void>;

export function SaveGeneratedTest(arg1:string,arg2:string):Promise<string>;

export function SaveResponseToRequest(arg1:string,arg2:string):Promise<void>;

export function SaveSchemaSnapshot(arg1:string):Promise<void>;

export function SaveTextResponse(arg1:string,arg2:string):Promise<void>;

export function SaveUpstashConfig(arg1:string,arg2:string):Promise<void>;

export function SendNotification(arg1:string,arg2:string):Promise<void>;

export function SendRequest(arg1:models.RequestPayload):Promise<models.ResponseResult>;

export function SendSocketIOMessage(arg1:string):Promise<void>;

export function SendSocketMessage(arg1:string):Promise<void>;

export function SetActiveEnvironment(arg1:string):Promise<void>;

export function SetAirGapConfig(arg1:string):Promise<void>;

export function SetAutoSync(arg1:boolean):Promise<void>;

export function SetCollectionVariables(arg1:string,arg2:Array<models.EnvVar>):Promise<void>;

export function SetDevProfilePublic(arg1:boolean):Promise<void>;

export function SetDiscordURL(arg1:string):Promise<void>;

export function SetEncryptionPassphrase(arg1:string):Promise<void>;

export function SetEnvVar(arg1:string,arg2:string):Promise<void>;

export function SetProxyConfig(arg1:string):Promise<void>;

export function SetRouteOverride(arg1:string,arg2:string,arg3:models.MockOverride):Promise<void>;

export function SetTelemetryEnabled(arg1:boolean):Promise<void>;

export function StartInterceptor():Promise<number>;

export function StartMockServer(arg1:number):Promise<main.MockStatus>;

export function StopInterceptor():Promise<void>;

export function StopMockServer():Promise<void>;

export function StoreSecret(arg1:vault.StoreSecretInput):Promise<vault.SecretReference>;

export function SwitchBranch(arg1:string):Promise<void>;

export function SwitchWorkspace(arg1:string):Promise<workspaces.Info>;

export function ToggleMaskingRule(arg1:string,arg2:boolean):Promise<void>;

export function ToggleMockRecording(arg1:boolean):Promise<void>;

export function ToggleSSOProvider(arg1:string):Promise<void>;

export function UnlockCollection(arg1:string):Promise<void>;

export function UpdateCollectionScripts(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateEnvironment(arg1:string,arg2:string,arg3:Array<models.EnvVar>):Promise<void>;

export function UpdateHistoryEntry(arg1:string,arg2:Record<string, any>):Promise<void>;

export function UpdateProfile(arg1:string,arg2:string):Promise<void>;

export function UpdateProject(arg1:string,arg2:any,arg3:any):Promise<projects.Project>;

export function UpdateSavedRequest(arg1:string,arg2:string,arg3:models.RequestPayload):Promise<void>;

export function UpdateSchedule(arg1:string,arg2:any,arg3:any,arg4:any):Promise<void>;

export function UpdateScriptRules(arg1:string,arg2:Array<models.PreSetVar>,arg3:Array<models.ExtractRule>):Promise<void>;

export function UpdateTestGroup(arg1:string,arg2:models.TestGroup):Promise<void>;

export function UpdateTestSuite(arg1:models.TestSuite):Promise<void>;

export function UpvoteFeatureRequest(arg1:string):Promise<void>;
